name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
    - v*
    - main
    types:
    - synchronize
    - edited
    - opened

permissions:
  pull-requests: write

jobs:
  semantic_pr:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Semantic Pull Request
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}

  health_check:
    needs: semantic_pr
    runs-on: "ubuntu-latest"
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: "npm"
        node-version: 20

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test

    - name: Run Lint
      run: npm run lint

    - name: Run Build
      run: npm run build

  # test action works running from the graph
  test-action:
    needs: semantic_pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    - name: Create some files
      run: |
        mkdir -p ./test
        echo "Hello, __NAME__" > ./1.txt
        echo "Hello, {{ NAME }}" > ./2.txt
        echo "__SECRET__" > ./3.txt

    - name: Test action
      uses: ./
      with:
        file: "./test/*.txt"
      env:
        NAME: "Eduardo"
        SECRET: '$\S^`!@#$%^&*()_+-={}|[]\:";<>?,./'


    - name: Assert file contents
      run: |
        cat ./test/1.txt
        cat ./test/2.txt
        cat ./test/3.txt

    # trigger action failure if content of test.txt is not "test"
    - name: Check file contents 1
      run: |
        if [ "$(cat ./test/1.txt)" != "Hello, Eduardo" ]; then
          echo "File contents are not as expected"
          exit 1
        fi

    - name: Check file contents 2
      run: |
        if [ "$(cat ./test/2.txt)" != "Hello, Eduardo" ]; then
          echo "File contents are not as expected"
          exit 1
        fi

    - name: Check file contents 3
      run: |
        if [ "$(cat ./test/3.txt)" != "$\S^`!@#$%^&*()_+-={}|[]\:";<>?,./" ]; then
          echo "File contents are not as expected"
          exit 1
        fi
