name: CI

on:
  pull_request:
    branches:
    - main
    - beta
    types:
    - synchronize
    - edited
    - opened

permissions:
  pull-requests: write

jobs:
  semantic_pr:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Semantic Pull Request
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}

  health_check:
    needs: semantic_pr
    runs-on: "ubuntu-latest"
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: "npm"
        node-version: 20

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test

    - name: Run Lint
      run: npm run lint

    - name: Run Build
      run: npm run build

    - name: Run Health Check
      uses: ./action.yml
      with:
        file: "./test.txt"

    - name: Asset file contents
      run: cat ./test.txt

  # test action works running from the graph
  test-action:
    needs: semantic_pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    - name: Test action
      uses: ./
      with:
        file: "./test.txt"
      env:
        NAME: "Eduardo"

    - name: Asset file contents
      run: cat ./test.txt

    # trigger action failure if content of test.txt is not "test"
    - name: Check file contents
      run: |
        if [ "$(cat ./test.txt)" != "Hello, Eduardo" ]; then
          echo "File contents are not as expected"
          exit 1
        fi
